#!/usr/bin/env python3
######################################################
#
# Filename    : Fibonacci.py
# Description : While-loop and Recursive Method to
#               generate the Fibonacci sequence
# Author      : Leonardo de Almeida
#
######################################################

import time

# Initial message to user
print("\nThis program generates the Fibonacci Series\n")

# Input from user
qty = -1
while qty not in(range(38)):
    try:
        qty = int(input("Enter the number of terms between 0 and 37: "))
    except ValueError:
        print("Please enter an integer between 0 and 37. Try again.")
        continue
    else:
        print("You entered an integer, but it is not between 0 and 37. Try again.")


# Print the terms chosen by the user to generate the sequence
print("\nThe terms to generate the sequence are:\n")
print(list((range(qty))))


##############################################
# Fibonacci series generated by a while-loop #
##############################################


def fibonacci_loop(n):
    if qty == 1:
        print("\nThe Fibonacci series for", qty, "term:\n")
        print("0")
    else:
        n1 = 0
        n2 = 1
        count = 1
        print("\nThe Fibonacci series for", qty, "terms, generated by a while loop:\n")
        while count <= qty:
            if count < qty:
                print(n1, end=' , ')
            else:
                print(n1)
            nth = n1 + n2
            n1, n2 = n2, nth
            count += 1

# Call the while-loop function


initial_time = time.time()
fibonacci_loop(qty)
elapsed_time = (time.time() - initial_time)*1000
print("\nTime elapsed to generate the Fibonacci sequence with a while-loop: ", elapsed_time, " ms")

####################################################
# Fibonacci series generated by a recursive method #
####################################################


def fibonacci_recursive(n):
    if n <= 1:
        return n
    else:
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)


print("\nThe Fibonacci series for", qty, "terms, generated by a recursive method:\n")
initial_time = time.time()
for i in range(qty):
    if i < (qty - 1):
        print((fibonacci_recursive(i)), end=' , ')
    else:
        print(fibonacci_recursive(i))
elapsed_time = (time.time() - initial_time)*1000
print("\nTime elapsed to generate the Fibonacci sequence with a recursive method: ", elapsed_time, "ms")

#######
# End #
#######

